const Images = {
  activeInfoIcon: require('../assets/images/Icons/icon-more-active.png'),
  activeLocationIcon: require('../assets/images/Icons/icon-venue-active.png'),
  activeNotificationIcon: require('../assets/images/Icons/icon-notification-active.png'),
  activeScheduleIcon: require('../assets/images/Icons/icon-schedule-active.png'),
  amazon: require('../assets/images/sponsors/img-sponsor-amazon-web-services.png'),
  api: require('../assets/images/Icons/icon-api-testing.png'),
  arrowIcon: require('../assets/images/Icons/icon-arrow.png'),
  backButton: require('../assets/images/Icons/back-button.png'),
  background: require('../assets/images/BG.png'),
  barista: require('../assets/images/img-barista.jpg'),
  blowhorn: require('../assets/images/Icons/icon-blowhorn.png'),
  breakfastBig: require('../assets/images/breakfast-bg-lrg.jpg'),
  breakfastBreak: require('../assets/images/breakfast.jpg'),
  bugsnag: require('../assets/images/sponsors/img-sponsor-bugsnag.png'),
  businessOregon: require('../assets/images/sponsors/img-sponsor-business-oregon.png'),
  buttonBackground: require('../assets/images/button-bg.png'),
  callstack: require('../assets/images/sponsors/img-sponsor-callstack.png'),
  capitalOne: require('../assets/images/sponsors/img-sponsor-capital-one.png'),
  chevronIcon: require('../assets/images/Icons/icon-chevron.png'),
  chevronRight: require('../assets/images/Icons/chevron-right.png'),
  chinesegarden: require('../assets/images/img-chinesegarden.jpg'),
  clearLogo: require('../assets/images/top_logo.png'),
  closeButton: require('../assets/images/Icons/close-button.png'),
  coffeeBig: require('../assets/images/coffee-bg-lg.jpg'),
  coffeeBreak: require('../assets/images/bg-coffee-break.jpg'),
  components: require('../assets/images/Icons/icon-components.png'),
  courier: require('../assets/images/img-courier.jpg'),
  crLogo: require('../assets/images/cr-logo.png'),
  deschutesBrewery: require('../assets/images/deschutes-brewery.jpg'),
  deviceInfo: require('../assets/images/Icons/icon-device-information.png'),
  directionsIcon: require('../assets/images/Icons/icon-directions.png'),
  echobind: require('../assets/images/sponsors/img-sponsor-echobind.png'),
  faq: require('../assets/images/Icons/faq-icon.png'),
  fatHeadBrewery: require('../assets/images/fat-head-brewery.jpg'),
  formidable: require('../assets/images/sponsors/img-sponsor-formidable.png'),
  githubIcon: require('../assets/images/Icons/icon-github-red.png'),
  gradArmory: require('../assets/images/grad_armory.png'),
  gudog: require('../assets/images/sponsors/img-sponsor-gudog.png'),
  hamburger: require('../assets/images/Icons/hamburger.png'),
  happyHour: require('../assets/images/bg-happy-hour.jpg'),
  healthsparq: require('../assets/images/sponsors/img-sponsor-healthsparq.png'),
  heartcoffee: require('../assets/images/img-heartcoffee.jpg'),
  home: require('../assets/images/Icons/icon-home.png'),
  ignite: require('../assets/images/ignite_logo.png'),
  igniteClear: require('../assets/images/ignite-logo-transparent.png'),
  inactiveInfoIcon: require('../assets/images/Icons/icon-more.png'),
  inactiveLocationIcon: require('../assets/images/Icons/icon-venue.png'),
  inactiveNotificationIcon: require('../assets/images/Icons/icon-notification-inactive.png'),
  inactiveScheduleIcon: require('../assets/images/Icons/icon-schedule.png'),
  instrument: require('../assets/images/sponsors/img-sponsor-instrument.png'),
  japanesegarden: require('../assets/images/img-japanesegarden.jpg'),
  launch: require('../assets/images/launch-icon.png'),
  littleBigBurger: require('../assets/images/little-big-burger.jpg'),
  logo: require('../assets/images/ir.png'),
  lunchBig: require('../assets/images/lunch-bg-lg.jpg'),
  lunchBreak: require('../assets/images/bg-lunch-break.jpg'),
  lyftButton: require('../assets/images/lyft-button.png'),
  markerIcon: require('../assets/images/Icons/icon-marker.png'),
  mls: require('../assets/images/sponsors/img-sponsor-major_league_soccer.png'),
  modus: require('../assets/images/sponsors/img-sponsor-modus-create.png'),
  nativeBase: require('../assets/images/sponsors/img-sponsor-native base.png'),
  omsi: require('../assets/images/img-omsi.jpg'),
  partyBig: require('../assets/images/afterparty-bg-lg.jpg'),
  partyBreak: require('../assets/images/bg-party.jpg'),
  paypal: require('../assets/images/sponsors/img-sponsor-paypal.png'),
  peets: require('../assets/images/img-peets.jpg'),
  phase10: require('../assets/images/Icons/sun-phases/phase10.png'),
  phase11: require('../assets/images/Icons/sun-phases/phase11.png'),
  phase12: require('../assets/images/Icons/sun-phases/phase12.png'),
  phase13: require('../assets/images/Icons/sun-phases/phase13.png'),
  phase14: require('../assets/images/Icons/sun-phases/phase14.png'),
  phase15: require('../assets/images/Icons/sun-phases/phase15.png'),
  phase16: require('../assets/images/Icons/sun-phases/phase16.png'),
  phase17: require('../assets/images/Icons/sun-phases/phase17.png'),
  phase18: require('../assets/images/Icons/sun-phases/phase18.png'),
  phase19: require('../assets/images/Icons/sun-phases/phase19.png'),
  phase1: require('../assets/images/Icons/sun-phases/phase1.png'),
  phase20: require('../assets/images/Icons/sun-phases/phase20.png'),
  phase21: require('../assets/images/Icons/sun-phases/phase21.png'),
  phase22: require('../assets/images/Icons/sun-phases/phase22.png'),
  phase2: require('../assets/images/Icons/sun-phases/phase2.png'),
  phase3: require('../assets/images/Icons/sun-phases/phase3.png'),
  phase4: require('../assets/images/Icons/sun-phases/phase4.png'),
  phase5: require('../assets/images/Icons/sun-phases/phase5.png'),
  phase6: require('../assets/images/Icons/sun-phases/phase6.png'),
  phase7: require('../assets/images/Icons/sun-phases/phase7.png'),
  phase8: require('../assets/images/Icons/sun-phases/phase8.png'),
  phase9: require('../assets/images/Icons/sun-phases/phase9.png'),
  pioneersquare: require('../assets/images/img-pioneersquare.jpg'),
  powells: require('../assets/images/img-powells.jpg'),
  purpleArrowIcon: require('../assets/images/Icons/icon-purple-arrow.png'),
  qlik: require('../assets/images/sponsors/img-sponsor-qlik.png'),
  qlikCoffee: require('../assets/images/sponsors/img-sponsor-qlik-coffee.png'),
  rangle: require('../assets/images/sponsors/img-sponsor-rangle.io.png'),
  ready: require('../assets/images/your-app.png'),
  salesforce: require('../assets/images/sponsors/img-sponsor-salesforce.png'),
  salt: require('../assets/images/img-saltnstraw.jpg'),
  slack: require('../assets/images/Icons/icon-slack.png'),
  sponsor: require('../assets/images/sponsor.png'),
  sqspLogo: require('../assets/images/sqsp-logo.png'),
  squarespace: require('../assets/images/sponsors/img-sponsor-squarespace.png'),
  squarespacePhoto: require('../assets/images/squarespace-photo.jpg'),
  stumptown: require('../assets/images/img-stumptown.jpg'),
  tastyNAlder: require('../assets/images/tasty-n-alder.jpg'),
  thankYou: require('../assets/images/bg-thank-you.jpg'),
  theArmory: require('../assets/images/the-armory.png'),
  theme: require('../assets/images/Icons/icon-theme.png'),
  tileBg: require('../assets/images/tile_bg.png'),
  training: require('../assets/images/sponsors/img-sponsor-react native training.png'),
  twitterIcon: require('../assets/images/Icons/icon-twitter-red.png'),
  uberButton: require('../assets/images/uber-button.png'),
  usageExamples: require('../assets/images/Icons/icon-usage-examples.png'),
  voodoo: require('../assets/images/img-voodoo.jpg'),
  waterfront: require('../assets/images/img-waterfront.jpg'),
};

Images.forLocalCache = [
  Images.activeInfoIcon,
  Images.activeLocationIcon,
  Images.activeNotificationIcon,
  Images.activeScheduleIcon,
  Images.inactiveInfoIcon,
  Images.inactiveLocationIcon,
  Images.inactiveNotificationIcon,
  Images.inactiveScheduleIcon,
  Images.breakfastBreak,
  Images.arrowIcon,
  Images.twitterIcon,
  Images.githubIcon,
  Images.slack,
  Images.blowhorn,
  Images.theArmory,
];

export default Images;
